swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error 





  /user/{id}/transactions/:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API for getting all user transactions for the current month
      parameters:
        - in: path
          name: id
          description: User Id
          required: true
          type: string
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            type : object
        "404":
          description: User not found
        "500":
          description: Internal Server Error
  /user/{id}/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API for getting a user transaction informations
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
        - in: path
          name: id
          description: Transaction id
          required: true
          type: string
      responses:
        "200":
          description: User Transaction information retrieved successfully
          schema:
            type: object
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API for updating a user transaction informations
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
        - in: path
          name: id
          description: Transaction id
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User Transaction information uptaded successfully
          schema:
            type: object
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error




      
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
# ------------------------------
  Transactions:
    properties:
      category:
        type: string
      note:
        type: string
  

# -----------------------------
        
        
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
#--------------------------------------New
  BankAccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          amount:
            type: number
          transactionNumber:
            type: number
          balanceType:
            type: string
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body: 
        type: object
        properties:
          id: 
            type: string
          date:
            type: string
            format: date-time
          description:
            type: string
          amount: 
            type: number
          balance:
            type: number
  TransactionDetailsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          category:
            type: string
          note: 
            type: string